# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('Longitude', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('rank', models.IntegerField(default=1)),
                ('votes', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-votes',),
            },
        ),
    ]
