# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('snippet',)},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('-votes', '-id')},
        ),
    ]
