# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20160830_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='photo',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
    ]
