# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20161012_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='mediaType',
            field=models.CharField(default='image', max_length=10),
            preserve_default=False,
        ),
    ]
